spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: gateway

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
